global:
  LogLevel: debug

db:
  Path: ./data/db/exporter

eth1:
  # ETH1 node WebSocket address
  ETH1Addr: ws://eth1-ws-ext.stage.bloxinfra.com/ws
  RegistryContractAddr: 0xFdFf361eD2b094730fDD8FA9658B370cE6cd4b10

eth2:
  BeaconNodeAddr: eth2-lh-prater-5052-ext.stage.bloxinfra.com:80
  Network: prater

p2p:
  # replace with your ip
  HostAddress:
